# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DEVTRAN <- function(parin, inpar, parnames, init, cmtnames, capture, funs, data, idata, OMEGA, SIGMA) {
    .Call('mrgsolve_DEVTRAN', PACKAGE = 'mrgsolve', parin, inpar, parnames, init, cmtnames, capture, funs, data, idata, OMEGA, SIGMA)
}

MVGAUSS <- function(OMEGA_, n) {
    .Call('mrgsolve_MVGAUSS', PACKAGE = 'mrgsolve', OMEGA_, n)
}

decorr <- function(x) {
    invisible(.Call('mrgsolve_decorr', PACKAGE = 'mrgsolve', x))
}

ZERO <- function(x) {
    .Call('mrgsolve_ZERO', PACKAGE = 'mrgsolve', x)
}

SUPERMATRIX <- function(a, keep_names) {
    .Call('mrgsolve_SUPERMATRIX', PACKAGE = 'mrgsolve', a, keep_names)
}

get_tokens <- function(code) {
    .Call('mrgsolve_get_tokens', PACKAGE = 'mrgsolve', code)
}

from_to <- function(a, b, ai, bi) {
    invisible(.Call('mrgsolve_from_to', PACKAGE = 'mrgsolve', a, b, ai, bi))
}

EXPAND_EVENTS <- function(idcol_, events, id) {
    .Call('mrgsolve_EXPAND_EVENTS', PACKAGE = 'mrgsolve', idcol_, events, id)
}

TOUCH_FUNS <- function(lparam, linit, Neta, Neps, capture, funs) {
    .Call('mrgsolve_TOUCH_FUNS', PACKAGE = 'mrgsolve', lparam, linit, Neta, Neps, capture, funs)
}

QUICKSIM <- function(parin, param, init, parnames, cmtnames, data, idata, capturei, funs) {
    .Call('mrgsolve_QUICKSIM', PACKAGE = 'mrgsolve', parin, param, init, parnames, cmtnames, data, idata, capturei, funs)
}

