# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DEVTRAN <- function(parin, inpar, parnames_, init, cmtnames_, funs, data, idata, OMEGA, SIGMA) {
    .Call('mrgsolve_DEVTRAN', PACKAGE = 'mrgsolve', parin, inpar, parnames_, init, cmtnames_, funs, data, idata, OMEGA, SIGMA)
}

EXPAND_EVENTS <- function(parin, events, id) {
    .Call('mrgsolve_EXPAND_EVENTS', PACKAGE = 'mrgsolve', parin, events, id)
}

test_stop <- function() {
    invisible(.Call('mrgsolve_test_stop', PACKAGE = 'mrgsolve'))
}

CALLINIT <- function(Nparam, Ninit, xifun) {
    .Call('mrgsolve_CALLINIT', PACKAGE = 'mrgsolve', Nparam, Ninit, xifun)
}

TOUCH_FUNS <- function(lparam, linit, xifun, xtfun, xdfun) {
    .Call('mrgsolve_TOUCH_FUNS', PACKAGE = 'mrgsolve', lparam, linit, xifun, xtfun, xdfun)
}

MVGAUSS <- function(OMEGA_, n, seed) {
    .Call('mrgsolve_MVGAUSS', PACKAGE = 'mrgsolve', OMEGA_, n, seed)
}

SIMRE <- function(n1, OMEGA, n2, SIGMA, seed) {
    .Call('mrgsolve_SIMRE', PACKAGE = 'mrgsolve', n1, OMEGA, n2, SIGMA, seed)
}

decorr <- function(x) {
    invisible(.Call('mrgsolve_decorr', PACKAGE = 'mrgsolve', x))
}

ZERO <- function(x) {
    .Call('mrgsolve_ZERO', PACKAGE = 'mrgsolve', x)
}

SUPERMATRIX <- function(a, keep_names) {
    .Call('mrgsolve_SUPERMATRIX', PACKAGE = 'mrgsolve', a, keep_names)
}

map_data_set <- function(data_, inpar, lc_) {
    .Call('mrgsolve_map_data_set', PACKAGE = 'mrgsolve', data_, inpar, lc_)
}

get_tokens <- function(code) {
    .Call('mrgsolve_get_tokens', PACKAGE = 'mrgsolve', code)
}

get_sep_tokens <- function(code) {
    .Call('mrgsolve_get_sep_tokens', PACKAGE = 'mrgsolve', code)
}

