# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DEVTRAN <- function(parin, inpar, parnames, init, cmtnames, capture, funs, data, idata, OMEGA, SIGMA, envir) {
    .Call(`_mrgsolve_DEVTRAN`, parin, inpar, parnames, init, cmtnames, capture, funs, data, idata, OMEGA, SIGMA, envir)
}

MVGAUSS <- function(OMEGA_, n) {
    .Call(`_mrgsolve_MVGAUSS`, OMEGA_, n)
}

dcorr <- function(x) {
    invisible(.Call(`_mrgsolve_dcorr`, x))
}

SUPERMATRIX <- function(a, keep_names) {
    .Call(`_mrgsolve_SUPERMATRIX`, a, keep_names)
}

get_tokens <- function(code) {
    .Call(`_mrgsolve_get_tokens`, code)
}

EXPAND_EVENTS <- function(idcol_, events, id) {
    .Call(`_mrgsolve_EXPAND_EVENTS`, idcol_, events, id)
}

EXPAND_OBSERVATIONS <- function(data, times, to_copy, next_pos) {
    .Call(`_mrgsolve_EXPAND_OBSERVATIONS`, data, times, to_copy, next_pos)
}

TOUCH_FUNS <- function(lparam, linit, Neta, Neps, capture, funs, envir) {
    .Call(`_mrgsolve_TOUCH_FUNS`, lparam, linit, Neta, Neps, capture, funs, envir)
}

